version: "3.8"

services:
  localstack:
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack-terraform}
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - MAIN_CONTAINER_NAME=${LOCALSTACK_DOCKER_NAME-localstack-terraform}
      - SERVICES=${SERVICES-lambda,apigateway,cloudwatch}
      - DATA_DIR=${DATA_DIR-var/lib/localstack/data}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - LAMBDA_REMOTE_DOCKER=true
    volumes:
      - "${TMPDIR:-/tmp}/localstack://var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"